import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Button, Box, Typography } from '@mui/material';
import ButtonNav from '../../components/ButtonNav';
import * as dotenv from 'dotenv'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <Box
        sx={{
          my: 4,
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'center',
          alignItems: 'center',
        }}
      >
      </Box>
        <ButtonNav />
        <Typography variant="h2" align="center" gutterBottom>
          ASTAR TOKEN GETTER
        </Typography>
        <Button variant="contained">connect wallet</Button>
      </main>
    </>
  )
}